apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-0e850d1376da8168e
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0e11fd602769b51ce
      my-new-stack-PublicSubnet02:
        id: subnet-055515cc582754b51
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-064696777f2be786d
      my-new-stack-PrivateSubnet02:
        id: subnet-0bd886e7dc71bb906

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true